# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (/tmp/crontab.VUgTTR/crontab installed on Mon Mar 21 15:35:40 2022)
# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
# Edit this file to introduce tasks to be run by cron.
#
# Each task to run has to be defined through a single line
# indicating with different fields when the task will be run
# and what command to run for the task
#
# To define the time you can provide concrete values for
# minute (m), hour (h), day of month (dom), month (mon),
# and day of week (dow) or use '*' in these fields (for 'any').#
# Notice that tasks will be started based on the cron's system
# daemon's notion of time and timezones.
#
# Output of the crontab jobs (including errors) is sent through
# email to the user the crontab file belongs to (unless redirected).
#
# For example, you can run a backup of all your user accounts
# at 5 a.m every week with:
# 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
#
# For more information see the manual pages of crontab(5) and cron(8)
#
# m h  dom mon dow   command
0 1,5,9,13,17,21 * * * ssh -t antctl@feanta.solar.pvt /home/antctl/starburst/femTools/src/starburstControl stop
1 1,5,9,13,17,21 * * * ssh -t antctl@feanta.solar.pvt /home/antctl/starburst/femTools/src/starburstControl start
0 4 * * * cp /ephem/radioflux.noa /home/sched/Dropbox/PythonCode/Current/tmp/txt
1 4 * * * cp /ephem/radioflux.noa /common/tmp/txt
0 7 * * 0 rsync -av --delete --progress --log-file=/home/sched/rsynclogs/rsync_common.log -e ssh --exclude={"/cdrom","/dev","/lost+found","/media","/mnt","/nas1","/nas4/","/nas5","/old_common"} / /media/sched/common_backup/

## Sync the default.antlist file to dpp before the TPCAL runs at 18:40 and 21:40 UT
35 18,21 * * * rsync -auv /home/sched/Dropbox/PythonCode/Current/default.antlist user@dpp:/home/user/default.antlist >> /tmp/antlist_sync.log 2>&1