# Edit this file to introduce tasks to be run by cron.
#
# Each task to run has to be defined through a single line
# indicating with different fields when the task will be run
# and what command to run for the task
#
# To define the time you can provide concrete values for
# minute (m), hour (h), day of month (dom), month (mon),
# and day of week (dow) or use '*' in these fields (for 'any').
#
# Notice that tasks will be started based on the cron's system
# daemon's notion of time and timezones.
#
# Output of the crontab jobs (including errors) is sent through
# email to the user the crontab file belongs to (unless redirected).
#
# For example, you can run a backup of all your user accounts
# at 5 a.m every week with:
# 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
#
# For more information see the manual pages of crontab(5) and cron(8)
#
# m h  dom mon dow   command
# 0 0 * * * /bin/bash -c 'cd /home/sjyu/eovsa-flarelist-ops && ./run_flarelist2sql.sh -t "$(date -d "2 days ago" "+\%Y-\%m-\%d \%H:\%M:\%S")" "$(date "+\%Y-\%m-\%d \%H:\%M:\%S")"'
# 0 0 * * * /bin/bash -c 'cd /home/sjyu/eovsa-flarelist-ops && ./run_flarelist2sql.sh -t "$(date -d "2 days ago" "+%Y-%m-%d %H:%M:%S")" "$(date "+%Y-%m-%d %H:%M:%S")"' >> $HOME/flarelist_update.log 2>&1
# 0 0 * * * /bin/bash -c 'cd /home/sjyu/eovsa-flarelist-ops && ./run_flarelist2sql.sh -t "$(date -d "15 days ago" "+\%Y-\%m-\%d \%H:\%M:\%S")" "$(date "+\%Y-\%m-\%d \%H:\%M:\%S")"' >> $HOME/flarelist_update.log 2>&1
# 0 12 * * * /bin/bash -c 'cd /home/sjyu/eovsa-flarelist-ops && ./run_flarelist2sql.sh -t "$(date -d "30 days ago" "+\%Y-\%m-\%d \%H:\%M:\%S")" "$(date "+\%Y-\%m-\%d \%H:\%M:\%S")"' >> $HOME/flarelist_update.log 2>&1

# Clean up temporary files generated by the query site every hour
0 * * * * /bin/bash /var/www/html/lwadata-query/utils/cleanup_tmp.sh >> /home/sjyu/cleanup.log 2>&1

# Update the query MySQL database every 6 hours
5 */6 * * * flock -n /tmp/run_queryweb_mysql.lock /bin/bash -l /var/www/html/lwadata-query/utils/run_queryweb_daily.sh --mysql

# Generate synoptic movies once a day (avoid partial-day movies)
30 2 * * * flock -n /tmp/run_queryweb_movie_daily.lock /bin/bash -l /var/www/html/lwadata-query/utils/run_queryweb_daily.sh --movie

# Run antlist sync every 5 minutes
*/5 * * * * /home/sjyu/bin/sync_antlist.sh

# Run once at reboot
@reboot /home/sjyu/bin/sync_antlist.sh

# Keep Grafana stateframe bridge healthy: check every minute and restart if down.
*/5 * * * * /bin/bash /common/python/eovsapy-src/eovsapy/shellScript/grafana_bridge_watchdog.sh >> /tmp/grafana_bridge_watchdog_cron.log 2>&1
